import { escapeText } from "./safe-markup.mjs";

/**
 * Renders the common owner-only detail shell. Markup slots are generated by
 * trusted local renderers; every user-controlled scalar is encoded here.
 */
export function renderMatchDetail({
  selectionLabel = "匹配详情",
  title = "",
  subtitle = "",
  priceLabel = "",
  facts = [],
  mediaMarkup = "",
  bodyMarkup = "",
  showShare = false,
  variant = "listing",
  backIconMarkup = "←",
  shareIconMarkup = "↗"
} = {}) {
  return `<section class="detail-screen ${variant === "tenant" ? "tenant-detail-screen" : ""}" data-match-detail>
    <div class="detail-topbar"><button data-action="back-match-detail" aria-label="返回候选">${backIconMarkup}</button><b>${escapeText(selectionLabel)}</b>${showShare ? `<button data-action="open-share" aria-label="分享房源">${shareIconMarkup}</button>` : "<span></span>"}</div>
    ${mediaMarkup}
    <div class="detail-sheet">
      ${title || subtitle || priceLabel ? `<div class="detail-title"><div>${title ? `<h1>${escapeText(title)}</h1>` : ""}${subtitle ? `<p>${escapeText(subtitle)}</p>` : ""}</div>${priceLabel ? `<b>${escapeText(priceLabel)}</b>` : ""}</div>` : ""}
      ${facts.length ? `<div class="detail-facts">${facts.map((fact) => `<span>${escapeText(fact)}</span>`).join("")}</div>` : ""}
      ${bodyMarkup}
    </div>
  </section>`;
}

export function bindMatchDetailActions(root, handlers = {}) {
  const listener = (event) => {
    const target = event.target.closest?.("[data-action]");
    if (!target || !root.contains(target)) return;
    handlers[target.dataset.action]?.({ target, event });
  };
  root.addEventListener("click", listener);
  return () => root.removeEventListener("click", listener);
}
